import { Country } from '../types';

export const COUNTRIES_DATABASE: Country[] = [
  // --- Americas (20) ---
  {
    id: 'usa',
    name: 'USA',
    code: 'US',
    flagEmoji: '🇺🇸',
    primaryColor: '#B22234',
    secondaryColor: '#FFFFFF',
    accentColor: '#3C3B6E',
    pattern: 'stars',
    continent: 'Americas',
    baseSpeed: 1.05,
    acceleration: 1.04,
    jumpPower: 1.06,
    agility: 1.02,
    stability: 1.08,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    code: 'BR',
    flagEmoji: '🇧🇷',
    primaryColor: '#009739',
    secondaryColor: '#FEDD00',
    accentColor: '#002776',
    pattern: 'circle',
    continent: 'Americas',
    baseSpeed: 1.08,
    acceleration: 1.06,
    jumpPower: 1.08,
    agility: 1.10,
    stability: 0.98,
  },
  {
    id: 'canada',
    name: 'Canada',
    code: 'CA',
    flagEmoji: '🇨🇦',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#D80027',
    pattern: 'bicolor-v',
    continent: 'Americas',
    baseSpeed: 1.02,
    acceleration: 1.01,
    jumpPower: 1.03,
    agility: 1.04,
    stability: 1.07,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'AR',
    flagEmoji: '🇦🇷',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    accentColor: '#F6B40E',
    pattern: 'sun',
    continent: 'Americas',
    baseSpeed: 1.07,
    acceleration: 1.05,
    jumpPower: 1.02,
    agility: 1.09,
    stability: 1.01,
  },
  {
    id: 'mexico',
    name: 'Mexico',
    code: 'MX',
    flagEmoji: '🇲🇽',
    primaryColor: '#006847',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    pattern: 'tricolor-v',
    continent: 'Americas',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.04,
    agility: 1.06,
    stability: 1.02,
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'CO',
    flagEmoji: '🇨🇴',
    primaryColor: '#FCD116',
    secondaryColor: '#003893',
    accentColor: '#CE1126',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.05,
    agility: 1.04,
    stability: 0.99,
  },
  {
    id: 'chile',
    name: 'Chile',
    code: 'CL',
    flagEmoji: '🇨🇱',
    primaryColor: '#D52B1E',
    secondaryColor: '#FFFFFF',
    accentColor: '#0039A6',
    pattern: 'diagonal',
    continent: 'Americas',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.02,
    stability: 1.03,
  },
  {
    id: 'peru',
    name: 'Peru',
    code: 'PE',
    flagEmoji: '🇵🇪',
    primaryColor: '#D91023',
    secondaryColor: '#FFFFFF',
    accentColor: '#D91023',
    pattern: 'tricolor-v',
    continent: 'Americas',
    baseSpeed: 0.99,
    acceleration: 1.01,
    jumpPower: 1.02,
    agility: 1.01,
    stability: 1.02,
  },
  {
    id: 'jamaica',
    name: 'Jamaica',
    code: 'JM',
    flagEmoji: '🇯🇲',
    primaryColor: '#009B3A',
    secondaryColor: '#FED100',
    accentColor: '#000000',
    pattern: 'cross',
    continent: 'Americas',
    baseSpeed: 1.12,
    acceleration: 1.10,
    jumpPower: 1.08,
    agility: 1.05,
    stability: 0.96,
  },
  {
    id: 'cuba',
    name: 'Cuba',
    code: 'CU',
    flagEmoji: '🇨🇺',
    primaryColor: '#002A8F',
    secondaryColor: '#FFFFFF',
    accentColor: '#CF142B',
    pattern: 'stripes-h',
    continent: 'Americas',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.01,
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    code: 'UY',
    flagEmoji: '🇺🇾',
    primaryColor: '#0038A8',
    secondaryColor: '#FFFFFF',
    accentColor: '#FCD116',
    pattern: 'sun',
    continent: 'Americas',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.01,
    agility: 1.04,
    stability: 1.05,
  },
  {
    id: 'costa_rica',
    name: 'Costa Rica',
    code: 'CR',
    flagEmoji: '🇨🇷',
    primaryColor: '#002B7F',
    secondaryColor: '#CE1126',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 1.00,
    acceleration: 1.01,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.00,
  },
  {
    id: 'venezuela',
    name: 'Venezuela',
    code: 'VE',
    flagEmoji: '🇻🇪',
    primaryColor: '#FCE300',
    secondaryColor: '#00247D',
    accentColor: '#CF142B',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 1.01,
    acceleration: 1.00,
    jumpPower: 1.01,
    agility: 1.02,
    stability: 0.99,
  },
  {
    id: 'panama',
    name: 'Panama',
    code: 'PA',
    flagEmoji: '🇵🇦',
    primaryColor: '#00529B',
    secondaryColor: '#D21034',
    accentColor: '#FFFFFF',
    pattern: 'bicolor-h',
    continent: 'Americas',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.01,
    agility: 1.02,
    stability: 1.01,
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    code: 'EC',
    flagEmoji: '🇪🇨',
    primaryColor: '#FFDD00',
    secondaryColor: '#034EA2',
    accentColor: '#ED1C24',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 0.99,
    acceleration: 1.01,
    jumpPower: 1.03,
    agility: 1.01,
    stability: 1.01,
  },
  {
    id: 'dominican_rep',
    name: 'Dominican Rep.',
    code: 'DO',
    flagEmoji: '🇩🇴',
    primaryColor: '#002F6C',
    secondaryColor: '#CE1126',
    accentColor: '#FFFFFF',
    pattern: 'cross',
    continent: 'Americas',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.01,
  },
  {
    id: 'trinidad_tobago',
    name: 'Trinidad & Tobago',
    code: 'TT',
    flagEmoji: '🇹🇹',
    primaryColor: '#CE1126',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
    pattern: 'diagonal',
    continent: 'Americas',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.05,
    agility: 1.04,
    stability: 1.00,
  },
  {
    id: 'bahamas',
    name: 'Bahamas',
    code: 'BS',
    flagEmoji: '🇧🇸',
    primaryColor: '#00778B',
    secondaryColor: '#FFC72C',
    accentColor: '#000000',
    pattern: 'diagonal',
    continent: 'Americas',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.06,
    agility: 1.05,
    stability: 0.99,
  },
  {
    id: 'paraguay',
    name: 'Paraguay',
    code: 'PY',
    flagEmoji: '🇵🇾',
    primaryColor: '#D52B1E',
    secondaryColor: '#FFFFFF',
    accentColor: '#0038A8',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.02,
  },
  {
    id: 'bolivia',
    name: 'Bolivia',
    code: 'BO',
    flagEmoji: '🇧🇴',
    primaryColor: '#D52B1E',
    secondaryColor: '#FCD116',
    accentColor: '#007934',
    pattern: 'tricolor-h',
    continent: 'Americas',
    baseSpeed: 1.00,
    acceleration: 1.01,
    jumpPower: 1.03,
    agility: 1.02,
    stability: 1.04,
  },

  // --- Europe (30) ---
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'GB',
    flagEmoji: '🇬🇧',
    primaryColor: '#012169',
    secondaryColor: '#C8102E',
    accentColor: '#FFFFFF',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.02,
    agility: 1.06,
    stability: 1.04,
  },
  {
    id: 'germany',
    name: 'Germany',
    code: 'DE',
    flagEmoji: '🇩🇪',
    primaryColor: '#000000',
    secondaryColor: '#DD0000',
    accentColor: '#FFCE00',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.06,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.10,
  },
  {
    id: 'france',
    name: 'France',
    code: 'FR',
    flagEmoji: '🇫🇷',
    primaryColor: '#002654',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    pattern: 'tricolor-v',
    continent: 'Europe',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.04,
    agility: 1.07,
    stability: 1.02,
  },
  {
    id: 'italy',
    name: 'Italy',
    code: 'IT',
    flagEmoji: '🇮🇹',
    primaryColor: '#009246',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE2B37',
    pattern: 'tricolor-v',
    continent: 'Europe',
    baseSpeed: 1.06,
    acceleration: 1.08,
    jumpPower: 1.02,
    agility: 1.08,
    stability: 0.99,
  },
  {
    id: 'spain',
    name: 'Spain',
    code: 'ES',
    flagEmoji: '🇪🇸',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    accentColor: '#AA151B',
    pattern: 'stripes-h',
    continent: 'Europe',
    baseSpeed: 1.05,
    acceleration: 1.05,
    jumpPower: 1.03,
    agility: 1.07,
    stability: 1.01,
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    code: 'NL',
    flagEmoji: '🇳🇱',
    primaryColor: '#FF4F00',
    secondaryColor: '#FFFFFF',
    accentColor: '#21468B',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.06,
    acceleration: 1.05,
    jumpPower: 1.04,
    agility: 1.06,
    stability: 1.03,
  },
  {
    id: 'sweden',
    name: 'Sweden',
    code: 'SE',
    flagEmoji: '🇸🇪',
    primaryColor: '#006AA7',
    secondaryColor: '#FECC00',
    accentColor: '#006AA7',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.05,
    agility: 1.04,
    stability: 1.06,
  },
  {
    id: 'norway',
    name: 'Norway',
    code: 'NO',
    flagEmoji: '🇳🇴',
    primaryColor: '#BA0C2F',
    secondaryColor: '#00205B',
    accentColor: '#FFFFFF',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.04,
    acceleration: 1.03,
    jumpPower: 1.06,
    agility: 1.03,
    stability: 1.07,
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    code: 'CH',
    flagEmoji: '🇨🇭',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.05,
    stability: 1.08,
  },
  {
    id: 'belgium',
    name: 'Belgium',
    code: 'BE',
    flagEmoji: '🇧🇪',
    primaryColor: '#000000',
    secondaryColor: '#FDDA24',
    accentColor: '#EF3340',
    pattern: 'tricolor-v',
    continent: 'Europe',
    baseSpeed: 1.04,
    acceleration: 1.03,
    jumpPower: 1.02,
    agility: 1.05,
    stability: 1.03,
  },
  {
    id: 'portugal',
    name: 'Portugal',
    code: 'PT',
    flagEmoji: '🇵🇹',
    primaryColor: '#006600',
    secondaryColor: '#FF0000',
    accentColor: '#FFFF00',
    pattern: 'bicolor-v',
    continent: 'Europe',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.03,
    agility: 1.06,
    stability: 1.01,
  },
  {
    id: 'austria',
    name: 'Austria',
    code: 'AT',
    flagEmoji: '🇦🇹',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.05,
    agility: 1.04,
    stability: 1.05,
  },
  {
    id: 'denmark',
    name: 'Denmark',
    code: 'DK',
    flagEmoji: '🇩🇰',
    primaryColor: '#C60C30',
    secondaryColor: '#FFFFFF',
    accentColor: '#C60C30',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.04,
    stability: 1.05,
  },
  {
    id: 'finland',
    name: 'Finland',
    code: 'FI',
    flagEmoji: '🇫🇮',
    primaryColor: '#002F6C',
    secondaryColor: '#FFFFFF',
    accentColor: '#002F6C',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.06,
  },
  {
    id: 'poland',
    name: 'Poland',
    code: 'PL',
    flagEmoji: '🇵🇱',
    primaryColor: '#FFFFFF',
    secondaryColor: '#DC143C',
    accentColor: '#DC143C',
    pattern: 'bicolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.02,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.04,
  },
  {
    id: 'greece',
    name: 'Greece',
    code: 'GR',
    flagEmoji: '🇬🇷',
    primaryColor: '#0D5EAF',
    secondaryColor: '#FFFFFF',
    accentColor: '#0D5EAF',
    pattern: 'stripes-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'ireland',
    name: 'Ireland',
    code: 'IE',
    flagEmoji: '🇮🇪',
    primaryColor: '#169B62',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF883E',
    pattern: 'tricolor-v',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.05,
    stability: 1.02,
  },
  {
    id: 'czechia',
    name: 'Czechia',
    code: 'CZ',
    flagEmoji: '🇨🇿',
    primaryColor: '#11457E',
    secondaryColor: '#D7141A',
    accentColor: '#FFFFFF',
    pattern: 'diagonal',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.04,
    stability: 1.04,
  },
  {
    id: 'hungary',
    name: 'Hungary',
    code: 'HU',
    flagEmoji: '🇭🇺',
    primaryColor: '#CE2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#477050',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.03,
  },
  {
    id: 'croatia',
    name: 'Croatia',
    code: 'HR',
    flagEmoji: '🇭🇷',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#171796',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.06,
    stability: 1.02,
  },
  {
    id: 'turkey',
    name: 'Turkey',
    code: 'TR',
    flagEmoji: '🇹🇷',
    primaryColor: '#E30A17',
    secondaryColor: '#FFFFFF',
    accentColor: '#E30A17',
    pattern: 'sun',
    continent: 'Europe',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.03,
  },
  {
    id: 'ukraine',
    name: 'Ukraine',
    code: 'UA',
    flagEmoji: '🇺🇦',
    primaryColor: '#005BBB',
    secondaryColor: '#FFD500',
    accentColor: '#005BBB',
    pattern: 'bicolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.04,
  },
  {
    id: 'romania',
    name: 'Romania',
    code: 'RO',
    flagEmoji: '🇷🇴',
    primaryColor: '#002B7F',
    secondaryColor: '#FCD116',
    accentColor: '#CE1126',
    pattern: 'tricolor-v',
    continent: 'Europe',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.02,
  },
  {
    id: 'iceland',
    name: 'Iceland',
    code: 'IS',
    flagEmoji: '🇮🇸',
    primaryColor: '#02529C',
    secondaryColor: '#DC1E35',
    accentColor: '#FFFFFF',
    pattern: 'cross',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.01,
    jumpPower: 1.05,
    agility: 1.03,
    stability: 1.08,
  },
  {
    id: 'serbia',
    name: 'Serbia',
    code: 'RS',
    flagEmoji: '🇷🇸',
    primaryColor: '#C6363C',
    secondaryColor: '#0C4076',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.03,
  },
  {
    id: 'monaco',
    name: 'Monaco',
    code: 'MC',
    flagEmoji: '🇲🇨',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    pattern: 'bicolor-h',
    continent: 'Europe',
    baseSpeed: 1.06,
    acceleration: 1.08,
    jumpPower: 1.02,
    agility: 1.08,
    stability: 1.00,
  },
  {
    id: 'slovakia',
    name: 'Slovakia',
    code: 'SK',
    flagEmoji: '🇸🇰',
    primaryColor: '#EE1C25',
    secondaryColor: '#0B3F82',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.02,
    stability: 1.04,
  },
  {
    id: 'bulgaria',
    name: 'Bulgaria',
    code: 'BG',
    flagEmoji: '🇧🇬',
    primaryColor: '#FFFFFF',
    secondaryColor: '#00966E',
    accentColor: '#D62612',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.02,
    stability: 1.03,
  },
  {
    id: 'slovenia',
    name: 'Slovenia',
    code: 'SI',
    flagEmoji: '🇸🇮',
    primaryColor: '#005DA4',
    secondaryColor: '#ED1C24',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.04,
  },
  {
    id: 'estonia',
    name: 'Estonia',
    code: 'EE',
    flagEmoji: '🇪🇪',
    primaryColor: '#0072CE',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Europe',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.05,
  },

  // --- Asia (25) ---
  {
    id: 'japan',
    name: 'Japan',
    code: 'JP',
    flagEmoji: '🇯🇵',
    primaryColor: '#BC002D',
    secondaryColor: '#FFFFFF',
    accentColor: '#BC002D',
    pattern: 'circle',
    continent: 'Asia',
    baseSpeed: 1.07,
    acceleration: 1.09,
    jumpPower: 1.05,
    agility: 1.09,
    stability: 1.02,
  },
  {
    id: 'south_korea',
    name: 'South Korea',
    code: 'KR',
    flagEmoji: '🇰🇷',
    primaryColor: '#CD2E3A',
    secondaryColor: '#0047A0',
    accentColor: '#000000',
    pattern: 'circle',
    continent: 'Asia',
    baseSpeed: 1.07,
    acceleration: 1.08,
    jumpPower: 1.06,
    agility: 1.08,
    stability: 1.01,
  },
  {
    id: 'china',
    name: 'China',
    code: 'CN',
    flagEmoji: '🇨🇳',
    primaryColor: '#DE2910',
    secondaryColor: '#FFDE00',
    accentColor: '#DE2910',
    pattern: 'stars',
    continent: 'Asia',
    baseSpeed: 1.06,
    acceleration: 1.07,
    jumpPower: 1.07,
    agility: 1.06,
    stability: 1.06,
  },
  {
    id: 'india',
    name: 'India',
    code: 'IN',
    flagEmoji: '🇮🇳',
    primaryColor: '#FF9933',
    secondaryColor: '#FFFFFF',
    accentColor: '#138808',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.04,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.05,
    stability: 1.02,
  },
  {
    id: 'saudi_arabia',
    name: 'Saudi Arabia',
    code: 'SA',
    flagEmoji: '🇸🇦',
    primaryColor: '#006C35',
    secondaryColor: '#FFFFFF',
    accentColor: '#006C35',
    pattern: 'solid',
    continent: 'Asia',
    baseSpeed: 1.04,
    acceleration: 1.04,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.05,
  },
  {
    id: 'uae',
    name: 'UAE',
    code: 'AE',
    flagEmoji: '🇦🇪',
    primaryColor: '#00732F',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.03,
    agility: 1.05,
    stability: 1.03,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    code: 'SG',
    flagEmoji: '🇸🇬',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    pattern: 'bicolor-h',
    continent: 'Asia',
    baseSpeed: 1.05,
    acceleration: 1.07,
    jumpPower: 1.03,
    agility: 1.07,
    stability: 1.03,
  },
  {
    id: 'thailand',
    name: 'Thailand',
    code: 'TH',
    flagEmoji: '🇹🇭',
    primaryColor: '#A51931',
    secondaryColor: '#2D2A4A',
    accentColor: '#F4F5F8',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.01,
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    code: 'ID',
    flagEmoji: '🇮🇩',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    pattern: 'bicolor-h',
    continent: 'Asia',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.04,
    stability: 1.01,
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    code: 'VN',
    flagEmoji: '🇻🇳',
    primaryColor: '#DA251D',
    secondaryColor: '#FFFF00',
    accentColor: '#DA251D',
    pattern: 'sun',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.01,
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    code: 'MY',
    flagEmoji: '🇲🇾',
    primaryColor: '#CC0000',
    secondaryColor: '#000066',
    accentColor: '#FFCC00',
    pattern: 'stripes-h',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.05,
    stability: 1.02,
  },
  {
    id: 'philippines',
    name: 'Philippines',
    code: 'PH',
    flagEmoji: '🇵🇭',
    primaryColor: '#0038A8',
    secondaryColor: '#CE1126',
    accentColor: '#FCD116',
    pattern: 'diagonal',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.05,
    agility: 1.06,
    stability: 1.00,
  },
  {
    id: 'qatar',
    name: 'Qatar',
    code: 'QA',
    flagEmoji: '🇶🇦',
    primaryColor: '#8D1B3D',
    secondaryColor: '#FFFFFF',
    accentColor: '#8D1B3D',
    pattern: 'bicolor-v',
    continent: 'Asia',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.04,
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    code: 'PK',
    flagEmoji: '🇵🇰',
    primaryColor: '#01411C',
    secondaryColor: '#FFFFFF',
    accentColor: '#01411C',
    pattern: 'bicolor-v',
    continent: 'Asia',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.02,
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    code: 'BD',
    flagEmoji: '🇧🇩',
    primaryColor: '#006A4E',
    secondaryColor: '#F42A41',
    accentColor: '#006A4E',
    pattern: 'circle',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.01,
  },
  {
    id: 'kazakhstan',
    name: 'Kazakhstan',
    code: 'KZ',
    flagEmoji: '🇰🇿',
    primaryColor: '#00AFCA',
    secondaryColor: '#FEC50C',
    accentColor: '#00AFCA',
    pattern: 'sun',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.05,
    agility: 1.03,
    stability: 1.07,
  },
  {
    id: 'uzbekistan',
    name: 'Uzbekistan',
    code: 'UZ',
    flagEmoji: '🇺🇿',
    primaryColor: '#1EB53A',
    secondaryColor: '#0099B5',
    accentColor: '#CE1126',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.05,
  },
  {
    id: 'kuwait',
    name: 'Kuwait',
    code: 'KW',
    flagEmoji: '🇰🇼',
    primaryColor: '#007A3D',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.03,
  },
  {
    id: 'bahrain',
    name: 'Bahrain',
    code: 'BH',
    flagEmoji: '🇧🇭',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    pattern: 'bicolor-v',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'oman',
    name: 'Oman',
    code: 'OM',
    flagEmoji: '🇴🇲',
    primaryColor: '#DB161B',
    secondaryColor: '#FFFFFF',
    accentColor: '#008000',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.02,
    stability: 1.03,
  },
  {
    id: 'jordan',
    name: 'Jordan',
    code: 'JO',
    flagEmoji: '🇯🇴',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    accentColor: '#007A3D',
    pattern: 'stars',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.02,
    stability: 1.02,
  },
  {
    id: 'lebanon',
    name: 'Lebanon',
    code: 'LB',
    flagEmoji: '🇱🇧',
    primaryColor: '#ED1C24',
    secondaryColor: '#FFFFFF',
    accentColor: '#00A651',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.03,
    stability: 1.01,
  },
  {
    id: 'iraq',
    name: 'Iraq',
    code: 'IQ',
    flagEmoji: '🇮🇶',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
    pattern: 'tricolor-h',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.02,
    agility: 1.02,
    stability: 1.03,
  },
  {
    id: 'mongolia',
    name: 'Mongolia',
    code: 'MN',
    flagEmoji: '🇲🇳',
    primaryColor: '#E4002B',
    secondaryColor: '#003DA5',
    accentColor: '#FFD100',
    pattern: 'sun',
    continent: 'Asia',
    baseSpeed: 1.03,
    acceleration: 1.02,
    jumpPower: 1.05,
    agility: 1.03,
    stability: 1.08,
  },
  {
    id: 'nepal',
    name: 'Nepal',
    code: 'NP',
    flagEmoji: '🇳🇵',
    primaryColor: '#DC143C',
    secondaryColor: '#003893',
    accentColor: '#FFFFFF',
    pattern: 'sun',
    continent: 'Asia',
    baseSpeed: 1.01,
    acceleration: 1.01,
    jumpPower: 1.08,
    agility: 1.04,
    stability: 1.07,
  },

  // --- Africa (18) ---
  {
    id: 'south_africa',
    name: 'South Africa',
    code: 'ZA',
    flagEmoji: '🇿🇦',
    primaryColor: '#007A3D',
    secondaryColor: '#FFB612',
    accentColor: '#002395',
    pattern: 'diagonal',
    continent: 'Africa',
    baseSpeed: 1.05,
    acceleration: 1.04,
    jumpPower: 1.05,
    agility: 1.06,
    stability: 1.04,
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    code: 'NG',
    flagEmoji: '🇳🇬',
    primaryColor: '#008751',
    secondaryColor: '#FFFFFF',
    accentColor: '#008751',
    pattern: 'tricolor-v',
    continent: 'Africa',
    baseSpeed: 1.07,
    acceleration: 1.08,
    jumpPower: 1.07,
    agility: 1.06,
    stability: 0.98,
  },
  {
    id: 'egypt',
    name: 'Egypt',
    code: 'EG',
    flagEmoji: '🇪🇬',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
    pattern: 'tricolor-h',
    continent: 'Africa',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.03,
  },
  {
    id: 'kenya',
    name: 'Kenya',
    code: 'KE',
    flagEmoji: '🇰🇪',
    primaryColor: '#006600',
    secondaryColor: '#BB0000',
    accentColor: '#000000',
    pattern: 'tricolor-h',
    continent: 'Africa',
    baseSpeed: 1.10,
    acceleration: 1.06,
    jumpPower: 1.07,
    agility: 1.07,
    stability: 1.03,
  },
  {
    id: 'morocco',
    name: 'Morocco',
    code: 'MA',
    flagEmoji: '🇲🇦',
    primaryColor: '#C1272D',
    secondaryColor: '#006233',
    accentColor: '#C1272D',
    pattern: 'sun',
    continent: 'Africa',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.03,
    agility: 1.06,
    stability: 1.02,
  },
  {
    id: 'ghana',
    name: 'Ghana',
    code: 'GH',
    flagEmoji: '🇬🇭',
    primaryColor: '#CE1126',
    secondaryColor: '#FCD116',
    accentColor: '#006B3F',
    pattern: 'tricolor-h',
    continent: 'Africa',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.05,
    agility: 1.05,
    stability: 0.99,
  },
  {
    id: 'ethiopia',
    name: 'Ethiopia',
    code: 'ET',
    flagEmoji: '🇪🇹',
    primaryColor: '#078930',
    secondaryColor: '#FCDD09',
    accentColor: '#DA121A',
    pattern: 'tricolor-h',
    continent: 'Africa',
    baseSpeed: 1.09,
    acceleration: 1.05,
    jumpPower: 1.08,
    agility: 1.06,
    stability: 1.04,
  },
  {
    id: 'senegal',
    name: 'Senegal',
    code: 'SN',
    flagEmoji: '🇸🇳',
    primaryColor: '#00853F',
    secondaryColor: '#FDEF42',
    accentColor: '#E31B23',
    pattern: 'tricolor-v',
    continent: 'Africa',
    baseSpeed: 1.06,
    acceleration: 1.07,
    jumpPower: 1.05,
    agility: 1.06,
    stability: 0.99,
  },
  {
    id: 'algeria',
    name: 'Algeria',
    code: 'DZ',
    flagEmoji: '🇩🇿',
    primaryColor: '#006633',
    secondaryColor: '#FFFFFF',
    accentColor: '#D21034',
    pattern: 'bicolor-v',
    continent: 'Africa',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.03,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'ivory_coast',
    name: 'Ivory Coast',
    code: 'CI',
    flagEmoji: '🇨🇮',
    primaryColor: '#F77F00',
    secondaryColor: '#FFFFFF',
    accentColor: '#009E60',
    pattern: 'tricolor-v',
    continent: 'Africa',
    baseSpeed: 1.05,
    acceleration: 1.06,
    jumpPower: 1.04,
    agility: 1.05,
    stability: 1.00,
  },
  {
    id: 'cameroon',
    name: 'Cameroon',
    code: 'CM',
    flagEmoji: '🇨🇲',
    primaryColor: '#007A5E',
    secondaryColor: '#CE1126',
    accentColor: '#FCD116',
    pattern: 'tricolor-v',
    continent: 'Africa',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.04,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'tunisia',
    name: 'Tunisia',
    code: 'TN',
    flagEmoji: '🇹🇳',
    primaryColor: '#E70013',
    secondaryColor: '#FFFFFF',
    accentColor: '#E70013',
    pattern: 'circle',
    continent: 'Africa',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.02,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'uganda',
    name: 'Uganda',
    code: 'UG',
    flagEmoji: '🇺🇬',
    primaryColor: '#000000',
    secondaryColor: '#FCDC04',
    accentColor: '#D90000',
    pattern: 'stripes-h',
    continent: 'Africa',
    baseSpeed: 1.06,
    acceleration: 1.05,
    jumpPower: 1.06,
    agility: 1.04,
    stability: 1.02,
  },
  {
    id: 'zambia',
    name: 'Zambia',
    code: 'ZM',
    flagEmoji: '🇿🇲',
    primaryColor: '#198A00',
    secondaryColor: '#EF7D00',
    accentColor: '#DE2010',
    pattern: 'solid',
    continent: 'Africa',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.02,
  },
  {
    id: 'zimbabwe',
    name: 'Zimbabwe',
    code: 'ZW',
    flagEmoji: '🇿🇼',
    primaryColor: '#006400',
    secondaryColor: '#FFD700',
    accentColor: '#D40000',
    pattern: 'stars',
    continent: 'Africa',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.02,
  },
  {
    id: 'namibia',
    name: 'Namibia',
    code: 'NA',
    flagEmoji: '🇳🇦',
    primaryColor: '#003580',
    secondaryColor: '#D21034',
    accentColor: '#009543',
    pattern: 'diagonal',
    continent: 'Africa',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.04,
    agility: 1.04,
    stability: 1.03,
  },
  {
    id: 'botswana',
    name: 'Botswana',
    code: 'BW',
    flagEmoji: '🇧🇼',
    primaryColor: '#75AADB',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
    pattern: 'tricolor-h',
    continent: 'Africa',
    baseSpeed: 1.05,
    acceleration: 1.07,
    jumpPower: 1.05,
    agility: 1.05,
    stability: 1.01,
  },
  {
    id: 'madagascar',
    name: 'Madagascar',
    code: 'MG',
    flagEmoji: '🇲🇬',
    primaryColor: '#FC3D32',
    secondaryColor: '#007E3A',
    accentColor: '#FFFFFF',
    pattern: 'bicolor-v',
    continent: 'Africa',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.01,
  },

  // --- Oceania (7) ---
  {
    id: 'australia',
    name: 'Australia',
    code: 'AU',
    flagEmoji: '🇦🇺',
    primaryColor: '#00008B',
    secondaryColor: '#FFD700',
    accentColor: '#008751',
    pattern: 'stars',
    continent: 'Oceania',
    baseSpeed: 1.06,
    acceleration: 1.05,
    jumpPower: 1.06,
    agility: 1.07,
    stability: 1.05,
  },
  {
    id: 'new_zealand',
    name: 'New Zealand',
    code: 'NZ',
    flagEmoji: '🇳🇿',
    primaryColor: '#00247D',
    secondaryColor: '#CC142B',
    accentColor: '#FFFFFF',
    pattern: 'stars',
    continent: 'Oceania',
    baseSpeed: 1.05,
    acceleration: 1.04,
    jumpPower: 1.06,
    agility: 1.06,
    stability: 1.07,
  },
  {
    id: 'fiji',
    name: 'Fiji',
    code: 'FJ',
    flagEmoji: '🇫🇯',
    primaryColor: '#68BFE5',
    secondaryColor: '#C8102E',
    accentColor: '#FFFFFF',
    pattern: 'cross',
    continent: 'Oceania',
    baseSpeed: 1.04,
    acceleration: 1.05,
    jumpPower: 1.06,
    agility: 1.06,
    stability: 1.02,
  },
  {
    id: 'papua_new_guinea',
    name: 'Papua New Guinea',
    code: 'PG',
    flagEmoji: '🇵🇬',
    primaryColor: '#CE1126',
    secondaryColor: '#000000',
    accentColor: '#FFD700',
    pattern: 'diagonal',
    continent: 'Oceania',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.03,
    stability: 1.03,
  },
  {
    id: 'samoa',
    name: 'Samoa',
    code: 'WS',
    flagEmoji: '🇼🇸',
    primaryColor: '#CE1126',
    secondaryColor: '#002B7F',
    accentColor: '#FFFFFF',
    pattern: 'stars',
    continent: 'Oceania',
    baseSpeed: 1.03,
    acceleration: 1.04,
    jumpPower: 1.05,
    agility: 1.04,
    stability: 1.05,
  },
  {
    id: 'tonga',
    name: 'Tonga',
    code: 'TO',
    flagEmoji: '🇹🇴',
    primaryColor: '#C10000',
    secondaryColor: '#FFFFFF',
    accentColor: '#C10000',
    pattern: 'cross',
    continent: 'Oceania',
    baseSpeed: 1.02,
    acceleration: 1.03,
    jumpPower: 1.04,
    agility: 1.02,
    stability: 1.06,
  },
  {
    id: 'vanuatu',
    name: 'Vanuatu',
    code: 'VU',
    flagEmoji: '🇻🇺',
    primaryColor: '#D21034',
    secondaryColor: '#009543',
    accentColor: '#FDCE12',
    pattern: 'diagonal',
    continent: 'Oceania',
    baseSpeed: 1.01,
    acceleration: 1.02,
    jumpPower: 1.03,
    agility: 1.03,
    stability: 1.02,
  },
];

export function getCountryById(id: string): Country {
  const found = COUNTRIES_DATABASE.find(c => c.id === id);
  return found || COUNTRIES_DATABASE[0];
}

export function getAllCountries(): Country[] {
  return [...COUNTRIES_DATABASE];
}
